import { readFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
const require = createRequire(`${process.env.BKGD_TEST_DEPENDENCIES || '/tmp/bkgd-quiz-check'}/package.json`)
const { initializeTestEnvironment, assertSucceeds, assertFails } = require('@firebase/rules-unit-testing')
const { doc, setDoc, getDoc, getDocs, collection, serverTimestamp, updateDoc, deleteDoc } = require('firebase/firestore')
const rules = await readFile(new URL('./firestore.rules.fragment', import.meta.url), 'utf8')
const env = await initializeTestEnvironment({ projectId: 'demo-design-thinking', firestore: { host: '127.0.0.1', port: 8080, rules: `rules_version = '2'; service cloud.firestore { match /databases/{database}/documents { ${rules} } }` } })
try {
 await env.clearFirestore()
 const student = env.authenticatedContext('student').firestore(), other = env.authenticatedContext('other').firestore(), admin = env.authenticatedContext('teacher').firestore(), guest = env.unauthenticatedContext().firestore()
 await env.withSecurityRulesDisabled(ctx => setDoc(doc(ctx.firestore(), 'design_thinking_admins', 'teacher'), { enabled: true }))
 const post = { uid: 'student', kind: 'briefing', text: 'Welche Funktionen braucht die App?', createdAt: serverTimestamp() }
 await assertSucceeds(getDoc(doc(student, 'design_thinking_posts', 'new')))
 await assertSucceeds(setDoc(doc(student, 'design_thinking_posts', 'new'), post))
 await assertSucceeds(getDoc(doc(student, 'design_thinking_posts', 'new')))
 await assertSucceeds(getDoc(doc(other, 'design_thinking_posts', 'new')))
 await assertFails(setDoc(doc(student, 'design_thinking_posts', 'new'), post))
 await assertFails(setDoc(doc(student, 'design_thinking_posts', 'invalid'), { ...post, color: '#3B82F6' }))
 await assertFails(setDoc(doc(student, 'design_thinking_posts', 'invalid'), { ...post, text: '' }))
 await assertFails(setDoc(doc(guest, 'design_thinking_posts', 'guest'), post))
 await assertFails(setDoc(doc(student, 'design_thinking_posts', 'spoof'), { ...post, uid: 'teacher' }))
 await assertSucceeds(getDocs(collection(student, 'design_thinking_posts')))
 await assertSucceeds(getDocs(collection(guest, 'design_thinking_posts')))
 await assertSucceeds(getDocs(collection(admin, 'design_thinking_posts')))
 await assertFails(setDoc(doc(student, 'design_thinking_admins', 'student'), { enabled: true }))
 const result = { rebriefing: 'Bearbeitete Antwort', problem: 'Wie können wir helfen?', sourceIds: ['new'], updatedBy: 'teacher', updatedAt: serverTimestamp() }
 await assertFails(setDoc(doc(student, 'design_thinking_results', 'current'), { ...result, updatedBy: 'student' }))
 await assertSucceeds(setDoc(doc(admin, 'design_thinking_results', 'current'), result))
 await assertSucceeds(getDoc(doc(student, 'design_thinking_results', 'current')))
 await assertSucceeds(setDoc(doc(admin, 'design_thinking_results', 'current'), { ...result, problem: 'Überarbeitete Problemfrage' }))
 await assertFails(updateDoc(doc(student, 'design_thinking_posts', 'new'), { text: 'Manipuliert' }))
 await assertFails(deleteDoc(doc(student, 'design_thinking_posts', 'new')))
 await assertFails(updateDoc(doc(admin, 'design_thinking_posts', 'new'), { uid: 'teacher' }))
 await assertFails(updateDoc(doc(admin, 'design_thinking_posts', 'new'), { text: '' }))
 await assertFails(updateDoc(doc(admin, 'design_thinking_posts', 'new'), { text: 'x'.repeat(5001) }))
 await assertSucceeds(updateDoc(doc(admin, 'design_thinking_posts', 'new'), { text: 'Bearbeitet' }))
 const edited = await getDoc(doc(guest, 'design_thinking_posts', 'new'))
 if (edited.data().text !== 'Bearbeitet') throw new Error('Edit not visible publicly')
 await assertSucceeds(deleteDoc(doc(admin, 'design_thinking_posts', 'new')))
 if ((await getDoc(doc(guest, 'design_thinking_posts', 'new'))).exists()) throw new Error('Deleted post still exists')

 await env.withSecurityRulesDisabled(async ctx => {
   for (const id of ['p1', 'p2', 'p3']) await setDoc(doc(ctx.firestore(), 'design_thinking_posts', id), { uid: 'student', kind: 'problem', text: id, createdAt: serverTimestamp() })
 })
 const ballot = ids => ({ postIds: ids, createdAt: serverTimestamp() })
 const ballotRef = doc(student, 'design_thinking_votes', 'student')
 await assertFails(setDoc(ballotRef, ballot([])))
 await assertFails(setDoc(ballotRef, ballot(['p1', 'p2', 'p3'])))
 await assertFails(setDoc(ballotRef, ballot(['p1', 'p1'])))
 await assertFails(setDoc(ballotRef, ballot(['missing'])))
 await assertFails(setDoc(doc(student, 'design_thinking_votes', 'other'), ballot(['p1'])))
 await assertSucceeds(setDoc(ballotRef, ballot(['p1', 'p2'])))
 await assertFails(setDoc(ballotRef, ballot(['p3'])))
 await assertFails(deleteDoc(ballotRef))
 await assertSucceeds(getDocs(collection(other, 'design_thinking_votes')))
 await assertSucceeds(setDoc(doc(other, 'design_thinking_votes', 'other'), ballot(['p1'])))

 await assertFails(deleteDoc(doc(other, 'design_thinking_votes', 'student')))
 await assertSucceeds(deleteDoc(doc(admin, 'design_thinking_votes', 'student')))
 await assertSucceeds(deleteDoc(doc(admin, 'design_thinking_votes', 'other')))
 if (!(await getDocs(collection(student, 'design_thinking_votes'))).empty) throw new Error('Reset did not clear votes')
 await assertSucceeds(setDoc(ballotRef, ballot(['p3'])))
 await assertFails(setDoc(ballotRef, ballot(['p1'])))
 console.log('PASS: student posts, color-free schema, public reads, admin-only post editing and deletion, protected metadata, published results readable.')
} finally { await env.cleanup() }
